import React, { useState } from 'react';
import { AppBar, Box, Button, Container, Divider, Drawer, IconButton, Toolbar, Typography } from '@mui/material';
import MenuIcon from '@mui/icons-material/Menu';
import FavoriteBorderIcon from '@mui/icons-material/FavoriteBorder';
import { Link as RouterLink } from 'react-router-dom';

type NavItem = { label: string; path: string; menu?: string[] };
const navItems: NavItem[] = [
  { label: 'Nhà đất bán', path: '/mua-ban', menu: ['Bán căn hộ chung cư', 'Bán chung cư mini, căn hộ dịch vụ', 'Bán nhà riêng', 'Bán nhà biệt thự, liền kề', 'Bán nhà mặt phố', 'Bán shophouse, nhà phố thương mại', 'Bán đất nền dự án', 'Bán đất', 'Bán trang trại, khu nghỉ dưỡng', 'Bán condotel', 'Bán kho, nhà xưởng', 'Bán loại bất động sản khác'] },
  { label: 'Nhà đất cho thuê', path: '/cho-thue', menu: ['Cho thuê căn hộ chung cư', 'Cho thuê chung cư mini, căn hộ dịch vụ', 'Cho thuê nhà riêng', 'Cho thuê nhà biệt thự, liền kề', 'Cho thuê nhà mặt phố', 'Cho thuê shophouse, nhà phố thương mại', 'Cho thuê nhà trọ, phòng trọ', 'Cho thuê văn phòng', 'Cho thuê, sang nhượng cửa hàng, ki ốt', 'Cho thuê kho, nhà xưởng, đất', 'Cho thuê loại bất động sản khác'] },
  { label: 'Dự án', path: '/du-an', menu: ['Căn hộ chung cư', 'Cao ốc văn phòng', 'Trung tâm thương mại', 'Khu đô thị mới', 'Khu phức hợp', 'Nhà ở xã hội', 'Khu nghỉ dưỡng, Sinh thái', 'Khu công nghiệp', 'Biệt thự, liền kề', 'Shophouse', 'Nhà mặt phố', 'Dự án khác'] },
  { label: 'Tin tức', path: '/tin-tuc' },
  { label: 'Wiki BĐS', path: '/wiki', menu: ['Mua BĐS', 'Bán BĐS', 'Thuê BĐS', 'Tài chính BĐS', 'Quy hoạch - Pháp lý', 'Nội - Ngoại thất', 'Phong thủy'] },
  { label: 'Phân tích đánh giá', path: '/phan-tich' },
  { label: 'Danh bạ', path: '/danh-ba', menu: ['Nhà môi giới', 'Doanh nghiệp'] }
];

const slugify = (value: string) => value.toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g, '').replace(/đ/g, 'd').replace(/[^a-z0-9]+/g, '-').replace(/(^-|-$)/g, '');

const Header: React.FC = () => {
  const [drawerOpen, setDrawerOpen] = useState(false);
  const [activeMenu, setActiveMenu] = useState<string | null>(null);
  const closeTimer = React.useRef<ReturnType<typeof setTimeout> | null>(null);
  const showMenu = (path: string) => { if (closeTimer.current) clearTimeout(closeTimer.current); setActiveMenu(path); };
  const hideMenu = () => { closeTimer.current = setTimeout(() => setActiveMenu(null), 140); };
  const nav = (mobile = false) => <Box sx={{ display: 'flex', flexDirection: { xs: 'column', lg: mobile ? 'column' : 'row' }, flexGrow: mobile ? 0 : 1 }}>{navItems.map((item) => <Box key={item.path} sx={{ position: 'relative' }} onMouseEnter={() => !mobile && item.menu && showMenu(item.path)} onMouseLeave={() => !mobile && item.menu && hideMenu()}><Button component={RouterLink} to={item.path} onClick={() => { setDrawerOpen(false); setActiveMenu(null); }} sx={{ color: '#202020', fontWeight: 600, textTransform: 'none', fontSize: 13, px: { lg: 1.15 }, minWidth: 0, py: 1.3, justifyContent: { xs: 'flex-start', lg: 'center' }, borderRadius: 0, '&:hover': { color: '#e53935', bgcolor: 'transparent' }, ...(activeMenu === item.path && !mobile ? { color: '#222', '&:after': { content: '""', position: 'absolute', bottom: 0, left: 9, right: 9, height: 2, bgcolor: '#e53935' } } : {}) }}>{item.label}</Button>{item.menu && activeMenu === item.path && !mobile && <Box onMouseEnter={() => showMenu(item.path)} onMouseLeave={hideMenu} sx={{ position: 'absolute', top: '100%', left: 0, zIndex: 1400, minWidth: item.path === '/danh-ba' ? 244 : 300, p: 1.25, bgcolor: '#fff', borderRadius: '0 0 10px 10px', boxShadow: '0 12px 26px rgba(0,0,0,.12)' }}>{item.menu.map((entry, index) => <Box key={entry} component={RouterLink} to={`${item.path}/${slugify(entry)}`} onClick={() => setActiveMenu(null)} sx={{ display: 'flex', alignItems: 'center', justifyContent: 'space-between', textDecoration: 'none', color: '#222', px: 1.1, py: .95, borderRadius: 1, fontSize: 14, whiteSpace: 'nowrap', '&:hover': { bgcolor: '#f7f7f7', color: '#e53935' } }}><span>{entry}</span>{index === 1 && (item.path === '/mua-ban' || item.path === '/cho-thue') && <Box component="span" sx={{ bgcolor: '#ef3d36', color: '#fff', borderRadius: .5, px: .55, py: .15, fontSize: 10, fontWeight: 700 }}>Mới</Box>}</Box>)}</Box>}</Box>)}</Box>;
  return <AppBar position="sticky" elevation={0} sx={{ bgcolor: '#fff', borderBottom: '1px solid #ececec' }}><Container maxWidth="xl"><Toolbar disableGutters sx={{ minHeight: { xs: 60, md: 72 }, gap: 1 }}><Box component={RouterLink} to="/" sx={{ display: 'flex', alignItems: 'center', textDecoration: 'none', mr: { xs: 'auto', lg: 2 } }}><img src="/bds-logo.svg" alt="Bất động sản" style={{ width: 145, height: 'auto' }} /></Box><Box sx={{ display: { xs: 'none', lg: 'flex' }, flexGrow: 1 }}>{nav()}</Box><Box sx={{ display: { xs: 'none', md: 'flex' }, alignItems: 'center', gap: 1 }}><Typography variant="body2" fontWeight={600} fontSize={12}>Tải ứng dụng</Typography><IconButton size="small"><FavoriteBorderIcon fontSize="small" /></IconButton><Divider orientation="vertical" flexItem sx={{ my: 2 }} /><Button component={RouterLink} to="/dang-nhap" color="inherit" sx={{ textTransform: 'none', fontSize: 12, fontWeight: 600 }}>Đăng nhập</Button><Button component={RouterLink} to="/dang-ky" color="inherit" sx={{ textTransform: 'none', fontSize: 12, fontWeight: 600 }}>Đăng ký</Button><Button component={RouterLink} to="/dang-tin" variant="outlined" sx={{ color: '#333', borderColor: '#ddd', textTransform: 'none', fontSize: 12, fontWeight: 700, px: 1.6 }}>Đăng tin</Button></Box><IconButton onClick={() => setDrawerOpen(true)} sx={{ display: { lg: 'none' } }}><MenuIcon /></IconButton></Toolbar></Container><Drawer anchor="right" open={drawerOpen} onClose={() => setDrawerOpen(false)}><Box sx={{ width: 290, p: 2 }}><Box component={RouterLink} to="/" onClick={() => setDrawerOpen(false)}><img src="/bds-logo.svg" alt="Bất động sản" style={{ width: 145 }} /></Box><Box mt={2}>{nav(true)}</Box></Box></Drawer></AppBar>;
};
export default Header;
